### Вычисления с помощью Numpy

**Задание 1**

In [2]:
import numpy as np

In [29]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [30]:
a = a.transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [32]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

**Задание 2**

In [34]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

**Задание 3**

In [59]:
a_centered[0:, 0]

array([-1.,  0.,  1.,  1., -1.])

In [52]:
a_centered[0:, 1:]

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [60]:
a_centered_sp = np.dot(a_centered[0:, 0], a_centered[0:, 1:])
a_centered_sp

array([8.])

In [63]:
a_centered_sp / (len(a) - 1)

array([2.])

**Задание 4**

In [65]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

### Работа с данными в Pandas

**Задание 1**

In [66]:
import pandas as pd

In [67]:
authors = pd.DataFrame({'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']},
                       columns = ['author_id', 'author_name'])

In [68]:
book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3],
                     'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо',
                                    'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price': [450, 300, 350, 500, 450, 370, 290]},
                    columns = ['author_id', 'book_title', 'price'])

**Задание 2**

In [75]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'right')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

**Задание 3**

In [77]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

**Задание 4**

In [89]:
authors_stat = pd.DataFrame({'author_name': authors_price.groupby('author_name'),
                             'min_price': authors_price.groupby('author_name')['price'].min(),
                             'max_price': authors_price.groupby('author_name')['price'].max(),
                             'mean_price': authors_price.groupby('author_name')['price'].mean()},
                           columns = ['min_price', 'max_price', 'mean_price'])
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

**Задание 5**

In [90]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [137]:
book_info = pd.pivot_table(authors_price, index='author_name', values='price', columns='cover', aggfunc='sum')
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      NaN
Тургенев      650.0    450.0
Чехов           NaN    950.0

In [138]:
book_info.fillna(0, inplace=True)
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [139]:
book_info.to_pickle('book_info.pkl')

In [141]:
book_info2 = pd.read_pickle('book_info.pkl')

In [142]:
book_info2

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [144]:
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True